#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc rule -a scratchpad sticky=on state=floating hidden=on
# check scratchpad already running
#[ "$(ps -x | grep -c 'scratchpad')" -eq "1" ] && st -c scratchpad -e ~/bin/scratch &

bspc rule -a dropdown sticky=on state=floating hidden=on
termite --class dropdown -e "zsh -i" &

polybar -q main -c "~/.config/polybar/forest/config.ini" &
feh --bg-fill ~/Wallpapers/task.png
picom -b&
st
